language: ruby
rvm:
  - 1.9.2
before_script:
  - "cp config/database.example.yml config/database.yml"
  - psql -c 'create database neday_test;' -U postgres
  - "RAILS_ENV=test bundle exec rake db:migrate"
script:
  - "bundle exec rspec"

