language: ruby
rvm:
  - 1.9.2
before_script:
  - "cp config/database.example.yml config/database.yml"
  - mysql -e 'create database neday_test;'
  - "RAILS_ENV=test bundle exec rake db:schema:load"
script:
  - "bundle exec rspec"

