mysql:
  adapter: mysql2
  database: neday_test
  username: root
  encoding: utf8

script: 'bundle exec rake db:schema:load && bundle exec rake db:seed &&  bundle exec rspec'
language: ruby
rvm:
  - 1.9.2

