development:
  fb:
    app_id: '166205056822008'
    app_secret: '8291b8e4090f9e36bb71ab564519c498'
  vk:
    app_id: '2773786'
    app_secret: 'Zq6VkORNGdMmYvmVxO80'
  twitter:
    consumer_key: '168426826-cMu1xQxCot7PavLvSN6FbTBKjZNp9Rg1b7ER7jf7'
    consumer_secret: 'gvB2ElkQBpYdrsg07qcozcEsywrZjBnAfjTYbdi8HX4'

test:

production:
  fb:
    app_id: '335195876511579'
    app_secret: '7dd87dcc985b6446257313358bda6811'
  vk:
    app_id: '2773815'
    app_secret: 'bcFSmH0yohYIcEGthe56'
  twitter:
    consumer_key: 'db8gYNPmMIuNiyy33aiTQ'
    consumer_secret: '5FzVqAAVJ9I26mZ1FYUnx2WGf0yApUzSgtC5Y8aLa8'
