development:
  fb:
    app_id: '166205056822008'
    app_secret: '8291b8e4090f9e36bb71ab564519c498'
  vk:
    app_id: '2773786'
    app_secret: 'Zq6VkORNGdMmYvmVxO80'
  twitter:
    consumer_key: 'vfeRImKs04QjpvIo8BP2g'
    consumer_secret: 'l8xjPC1uPyppAQ9TSiOr5wHFT7BmTUQ5T0TIhYNY1k'
  file_storage: :file
  yandex:
    api_key: AMP9OE8BAAAA1OzcaAIAORTRZkjUzTo7c1OSFZMG3MAvO6YAAAAAAAAAAACn81NB7MEFHXzYbu2SlUjxpV8nGQ==
  google:
    app_id: 232331970718.apps.googleusercontent.com
    app_secret: YQwUS7ez3gz8uhH9X7LcVmLv
test:
  fb:
    app_id: '166205056822008'
    app_secret: '8291b8e4090f9e36bb71ab564519c498'
  vk:
    app_id: '2773786'
    app_secret: 'Zq6VkORNGdMmYvmVxO80'
  twitter:
    consumer_key: 'vfeRImKs04QjpvIo8BP2g'
    consumer_secret: 'l8xjPC1uPyppAQ9TSiOr5wHFT7BmTUQ5T0TIhYNY1k'
  file_storage: :file
  yandex:
    api_key: AMP9OE8BAAAA1OzcaAIAORTRZkjUzTo7c1OSFZMG3MAvO6YAAAAAAAAAAACn81NB7MEFHXzYbu2SlUjxpV8nGQ==
  google:
    app_id: 232331970718.apps.googleusercontent.com
    app_secret: YQwUS7ez3gz8uhH9X7LcVmLv

production:
  fb:
    app_id: '335195876511579'
    app_secret: '7dd87dcc985b6446257313358bda6811'
  vk:
    app_id: '2773815'
    app_secret: 'bcFSmH0yohYIcEGthe56'
  twitter:
    consumer_key: 'db8gYNPmMIuNiyy33aiTQ'
    consumer_secret: '5FzVqAAVJ9I26mZ1FYUnx2WGf0yApUzSgtC5Y8aLa8'
  file_storage: :s3
  yandex:
    api_key: ABz-OE8BAAAAZuWjWwIA9iau7jfHC1OfDJM4GROyvAnyggUAAAAAAAAAAAD52P9xkc6BYKbQfqFojK_Zo_d67A==
  google:
    app_id: 926147355465.apps.googleusercontent.com
    app_secret: TW_QW4cu6hK0msjXFi3q80la
